SELECT
    LINHA, 
    YEAR(DATA_VENDA) AS ANO, 
    MONTH(DATA_VENDA) AS MES, 
    SUM(QTD_VENDA) AS QTD_VENDA
FROM vendas
GROUP BY MARCA, YEAR(DATA_VENDA), MONTH(DATA_VENDA)
ORDER BY MARCA, ANO, MES